### ISSUE TITLE
Regarding starprompt model

### ISSUE THREAD

**Issue by alforhad** [aimagelab/mammoth#47]
**I am attempting to execute the starprompt model using the command below:**

`python ./utils/main.py --model starprompt --dataset seq-cifar100 --lr 0.01`

**And it's showing the following error.**

WARNING:root:Warning: python-dotenv not installed. Ignoring .env file.
/home/envs/mammoth/lib/python3.10/site-packages/kornia/feature/lightglue.py:44: FutureWarning: `torch.cuda.amp.custom_fwd(args...)` is deprecated. Please use `torch.amp.custom_fwd(args..., device_type='cuda')` instead.
  @torch.cuda.amp.custom_fwd(cast_inputs=torch.float32)
ERROR:root:Could not retrieve git hash.
Using device cuda:0
Using ResNet as backbone
Files already downloaded and verified
Traceback (most recent call last):
  File "/home/Downloads/mammoth-master/./utils/main.py", line 272, in <module>
    main()
  File "/home/Downloads/mammoth-master/./utils/main.py", line 230, in main
    model = get_model(args, backbone, loss, dataset.get_transform())
  File "/home/Downloads/mammoth-master/models/__init__.py", line 46, in get_model
    return get_model_class(args)(backbone, loss, args, transform)
  File "/home/Downloads/mammoth-master/models/starprompt.py", line 97, in __init__
    self.net = STARPromptModel(args,
  File "/home/Downloads/mammoth-master/models/star_prompt_utils/end_to_end_model.py", line 42, in __init__
    self.second_stage = SecondStageModel(args=args, num_classes=num_classes,
  File "/home/Downloads/mammoth-master/models/star_prompt_utils/second_stage_model.py", line 363, in __init__
    assert 'resnet' not in str(type(backbone)).lower(), "ResNet not supported"
AssertionError: ResNet not supported

**Comment by loribonna** [comment]
Hi @alforhad, the `seq-cifar100` uses `resnet18` as the default backbone since the images are not resized to 224. STAR-Prompt instead requires a ViT and images of resolution 224x224, so you should use `seq-cifar100-224` instead. Let me know if it works by running:
`python ./utils/main.py --model starprompt --dataset seq-cifar100-224 --lr 0.01`

**Comment by alforhad** [comment]
It works. Thanks.
